//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_ly_thiet_bị
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public string ID_HISTORY { get; set; }
        public string ID_DEVICE { get; set; }
        public Nullable<System.DateTime> UPDATE_CHECK { get; set; }
        public Nullable<int> INFOCHECK { get; set; }
        public string NOTE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string ID_USER { get; set; }
    
        public virtual DEVICE DEVICE { get; set; }
    }
}
